---

- name: 'Install Postman via AUR'
  shell:
   cmd: 'paru -S postman-bin'
  when: ansible_facts['os_family'] == "Manjaro"

- name: "Install Postman"
  unarchive:
    src: https://dl.pstmn.io/download/latest/linux64
    dest: /opt
    remote_src: yes
    creates: /opt/Postman/Postman
  when: ansible_facts['os_family'] == "Ubuntu"

- name: "Ensure local applications folder exists"
  file:
    path: /usr/local/share/applications
    state: directory
  when: ansible_facts['os_family'] == "Ubuntu"

- name: "Add Postman desktop file"
  copy:
    src: files/postman.desktop
    dest: /usr/local/share/applications/postman.desktop
  when: ansible_facts['os_family'] == "Ubuntu"
