---

- name: Install Postman
  ansible.builtin.include_tasks: 'ubuntu.yml'
  when: ansible_facts['os_family'] == "Debian"

- name: Install Postman
  ansible.builtin.include_tasks: 'arch.yml'
  when: ansible_facts['os_family'] == "Archlinux"
