---

- name: 'Install Packages Manjaro/Arch'
  become: true
  shell:
    cmd: "pacman -S {{ packages | join(' ') }} --noconfirm --needed"
  when: ansible_facts['os_family'] == "Archlinux"

- name: 'Install Packages Ubuntu'
  become: true
  apt:
    name: '{{ item }}'
    state: present
  when: ansible_facts['os_family'] == "Ubuntu"
  with_items: '{{ packages }}'
