---

- name: 'Install Packages Manjaro/Arch'
  become: true
  ansible.builtin.shell:
    cmd: "pacman -S {{ packages | join(' ') }} --noconfirm --needed"
  when: ansible_facts['os_family'] == "Archlinux"

- name: 'Install Packages Debian'
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  when: ansible_facts['os_family'] == "Debian"
  with_items: '{{ packages }}'
