---
- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: update & upgrade all package to latest version on ubuntu
  register: updatesys
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 36000

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
