---

- include_tasks: 'install-ubuntu.yml'
  when: ansible_facts['os_family'] == "Ubuntu"

- include_tasks: 'install-arch.yml'
  when: ansible_facts['os_family'] == "Archlinux"

- name: 'Set default'
  become: false
  shell:
    cmd: "rustup default {{ channel }}"
