---
# code: language=ansible

- name: 'Download rustup from url'
  get_url:
    dest: '/tmp/rustup'
    url: https://sh.rustup.rs
    mode: 0755
  when: ansible_facts['os_family'] == "Ubuntu"

- name: 'Install {{ channel }} rust and tools'
  shell:
   cmd: './rustup -q --profile {{ channel }}'
   chdir: /tmp
  when: ansible_facts['os_family'] == "Ubuntu"

- name: 'Install Rustup'
  become: false
  when: ansible_facts['os_family'] == "Archlinux"
  debug:
    msg: '{{ ansible_facts }}'

- name: 'Install Rustup'
  include_role:
    name: GROG.package
  vars:
    package_list:
      - name: rustup
        pacman: rustup
        apt_ignore: yes

- name: 'Install {{ channel }} rust and tools'
  become: false
  shell:
   cmd: "rustup install {{ channel }} --profile {{ profile | default('default') }}"

- name: 'Set default'
  become: false
  shell:
    cmd: "rustup default {{ channel }}"

- name: 'Remove Rustup shell script'
  file:
    state: absent
    path: /tmp/rustup
  when: ansible_facts['os_family'] == "Ubuntu"

- name: Set up Rust Env
  become: false
  blockinfile:
    path: '{{ item }}'
    marker: "### {mark} Ansible managed: Rust"
    block: |
      . "$HOME/.cargo/env"
  with_items:
   - "{{ lookup('env', 'HOME') }}/.bashrc"
   - "{{ lookup('env', 'HOME') }}/.zshrc"
