---

- name: "Install Starship"
  include_role:
    name: GROG.package
  vars:
    package_list:
      - name: starship
        pacman: starship
        apt_ignore: yes

- name: 'Remove Shell config file'
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.{{ shell }}rc"
    state: absent
    mode: '0644'
  when: clear_file

- name: 'Adding Shell config file'
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.{{ shell }}rc"
    mode: '0644'
    state: touch
  when: clear_file and (shell == "bash" or shell == "zsh")

- name: 'Adding Starship config folder'
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: 'Adding Starship config file'
  template:
    dest: "{{ lookup('env', 'HOME') }}/.config/starship.toml"
    src: files/starship.toml
    force: true

- name: "Setup Starship in Shell Config"
  become: false
  blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.{{ shell }}rc"
    marker: "### {mark} Ansible managed: StarShip"
    block: |
     eval "$(starship init {{ shell }})"
  when: shell == "bash" or shell == "zsh"
