---

- name: 'Download Hosts-Edit from Github'
  become: false
  ansible.builtin.git:
    accept_newhostkey: yes
    clone: yes
    dest: /tmp/hosts-edit
    repo: https://github.com/malusev998/hosts.git
  environment:
    GIT_TERMINAL_PROMPT: '0'

- name: Compile Hosts-Edit
  become: false
  ansible.builtin.shell:
    cmd: cargo build --profile dist --all
    chdir: /tmp/hosts-edit

- name: 'Create bin dir'
  become: false
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/bin"
    state: directory

- name: Install Hosts-Edit
  become: false
  ansible.builtin.copy:
    dest: "{{ lookup('env', 'HOME') }}/bin/hosts"
    src: /tmp/hosts-edit/target/dist/hosts-edit
    mode: '0755'
    remote_src: no

- name: 'Remove Hosts-Edit from temp dir'
  ignore_errors: true
  ansible.builtin.file:
    path: /tmp/hosts-edit
    state: absent

- name: "Setup {{ lookup('env', 'HOME') }}/bin in PATH"
  become: false
  blockinfile:
    path: '{{ item }}'
    marker: "### {mark} Ansible managed: $HOME/bin"
    block: |
      export PATH="$PATH:$HOME/bin"
  with_items:
   - "{{ lookup('env', 'HOME') }}/.bashrc"
   - "{{ lookup('env', 'HOME') }}/.zshrc"
