- name: Install AUR packages
  become: false
  shell:
    cmd: "paru -S {{ packages | join(' ') }} --nouseask --noconfirm --needed --removemake --noupgrademenu --noinstalldebug --cleanafter --nokeepsrc"
