---

- name: 'Install Go Manjaro/Arch'
  shell:
    cmd: 'pacman -S go --noconfirm --needed'
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install Go
  unarchive:
    src: https://dl.google.com/go{{ go_version }}.linux-amd64.tar.gz
    dest: /usr/local/go
    remote_src: yes
    creates: /usr/local/go/bin/go
  register: go_download
  when: ansible_facts['os_family'] == "Ubuntu"

- name: Set up Go Env
  become: false
  blockinfile:
    path: '{{ item }}'
    marker: "### {mark} Ansible managed: GoLang"
    block: |
      export GOPATH=$HOME/go
      export PATH="$PATH:$GOPATH/bin:/usr/local/go/bin"
  with_items:
   - "{{ ansible_env.USER }}/.bashrc"
   - "{{ ansible_env.USER }}/.zshrc"

- name: Install Go Packages
  shell:
   cmd: 'go install {{ item }}'
  with_items: '{{ go_packages }}'
