- name: Read SSH public key to authorize
  ansible.builtin.shell: 'cat {{ ssh_pub_key_path }}'
  register: ssh_pub_key

- name: Authorize key with GitHub
  community.general.github_key:
    vars:
      force: yes
      name: Access Key for Some Machine
      token: '{{ github_access_token }}'
      pubkey: '{{ ssh_pub_key.stdout }}'
