- name: Read SSH public key to authorize
  ansible.builtin.shell: 'cat {{ ssh_pub_key_path }}'
  register: ssh_pub_key

- name: Authorize key with GitHub
  community.general.github_key:
    force: yes
    name: "{{ key_name | default('NewPublicKeyFromAnsible') }}"
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'
