- name: Install KVM
  become: true
  ansible.builtin.include_role: "install.package"
  vars:
    packages:
      - virt-manager
      - qemu-desktop
      - libvirt
      - edk2-ovmf
      - dnsmasq
      - vde2
      - bridge-utils
      - iptables-nft
      - dmidecode

- name: Add KVM Group
  become: true
  ansible.builtin.group:
    name: kvm
    state: present
    system: true

- name: Add libvirt Group
  become: true
  ansible.builtin.group:
    name: libvirt
    state: present
    system: true

- name: Add User to KVM Group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: kvm
    append: true

- name: Add User to KVM Group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: libvirt
    append: true

- name: Add Groups to libvirtd.conf
  become: true
  ansible.builtin.blockinfile:
    path: "/etc/libvirt/libvirtd.conf"
    marker: "### {mark} Ansible managed: Groups"
    content: |
      unix_sock_group = "libvirt"
      unix_sock_ro_perms = "0777"
      unix_sock_rw_perms = "0770"

- name: Add Groups to qemu.conf
  become: true
  ansible.builtin.blockinfile:
    path: "/etc/libvirt/qemu.conf"
    marker: "### {mark} Ansible managed: Groups"
    content: |
      swtpm_user = "swtpm"
      swtpm_group = "swtpm"
      user = "{{ ansible_env.USER }}"
      group = "{{ ansible_env.USER }}"

- name: Enable Service
  become: true
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: true

- name: net-autostart
  become: true
  ansible.builtin.shell: 'virsh net-autostart default'