---
- name: SSHD Config
  become: true
  ansible.builtin.template:
    src: files/sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0644"

- name: Restart SSH Server
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Install and Configure ZSH
  ansible.builtin.include_tasks: "zsh.yml"

- name: Alacritty Config
  become: true
  ansible.builtin.template:
    src: files/.alacritty.yml
    mode: "0644"
    dest: "{{ lookup('env', 'HOME') }}/.alacritty.yml"

- name: Set up Aliases
  become: false
  vars:
    aliases: "{{ lookup('file', 'files/.aliases') }}"
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    marker: "### {mark} Ansible managed: Aliases"
    content: "{{ aliases }}"
  with_items:
    - "{{ lookup('env', 'HOME') }}/.zshrc"

- name: Set up SSH Editor
  become: false
  vars:
    ssh_shell: "{{ lookup('file', 'files/.ssh_shell') }}"
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    marker: "### {mark} Ansible managed: SSH Shell"
    content: "{{ ssh_shell }}"
  with_items:
    - "{{ lookup('env', 'HOME') }}/.zshrc"

- name: Set up Variables
  become: false
  vars:
    default_vars: "{{ lookup('file', 'files/.variables') }}"
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    marker: "### {mark} Ansible managed: Variables"
    content: "{{ default_vars }}"
  with_items:
    - "{{ lookup('env', 'HOME') }}/.zshrc"

- name: Setup Git Config
  become: false
  ansible.builtin.template:
    src: files/.gitconfig.j2
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
