---

- name: Create SSH Directory
  become: false
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory

- name: "Generate SSH key"
  become: false
  community.crypto.openssh_keypair:
    path: "{{ lookup('env', 'HOME') }}/.ssh/{{ ssh_key_filename | default('id_ed25519') }}"
    type: ed25519
    state: present
    force: no
    comment: "{{ email | default('dusan@dusanmalusev.dev') }}"
