---

- name: Install Docker
  ansible.builtin.include_tasks: 'ubuntu.yml'
  when: ansible_facts['os_family'] == "Debian"

- name: Install Docker
  ansible.builtin.include_tasks: 'arch.yml'
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install python docker module
  become: false
  ansible.builtin.pip:
    state: latest
    name:
      - docker
      - docker-compose

- name: "Adding existing user to Docker group"
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true

- name: Ensure docker daemon is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
