---

- name: 'Install Neovim Ubuntu'
  apt:
    name: neovim
    state: present
  when: ansible_facts['os_family'] == "Ubuntu"

- name: 'Install Neovim Manjaro/Arch'
  shell:
    cmd: 'pacman -S neovim --noconfirm --needed'
  when: ansible_facts['os_family'] == "Archlinux"

- name: 'Download Neovim Configuration'
  become: false
  ansible.builtin.git:
    accept_newhostkey: yes
    clone: yes
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    repo: git@github.com:malusev998/nvim.git
  environment:
    GIT_TERMINAL_PROMPT: '0'

- name: Install root npm packages for neovim
  npm:
    name: '{{ item }}'
    state: latest
    global: yes
  with_items:
    - pyright
    - typescript-language-server
    - bash-language-server
    - vscode-langservers-extracted
    - dockerfile-language-server-nodejs
    - intelephense
    - yaml-language-server
    - neovim

- name: Install bottle python package
  ansible.builtin.pip:
    name: pyvim
    state: latest
