---
# code: language=ansible

- name: 'Download Paru from Github'
  ansible.builtin.git:
    accept_newhostkey: yes
    clone: yes
    dest: /tmp/paru
    repo: https://aur.archlinux.org/paru.git
  environment:
    GIT_TERMINAL_PROMPT: '0'

- name: 'Compile and install Paru'
  shell:
    cmd: 'makepkg -si --noconfirm --needed --noprogressbar'
    chdir: /tmp/paru

- name: 'Remove paru from temp dir'
  file:
    path: /tmp/paru
    state: absent
