---

- include_tasks: 'ubuntu-repo.yml'
  when: ansible_facts['os_family'] == "Ubuntu"

- name: Install NodeJS from Official Repositories
  include_role:
    name: GROG.package
  vars:
    package_list:
      - name: nodejs
        pacman: nodejs
        apt: nodejs
      - name: npm
        pacman: npm
        apt: npm

- name: Install yarn and pnpm
  npm:
    name: '{{ item }}'
    state: latest
    global: yes
  with_items:
    - pnpm
    - yarn
